#!/usr/bin/env python3
"""Build the combined fish_par viewer prototype from the three per-year viewers."""
import re, json, pathlib

HOME = pathlib.Path.home()
GH = HOME / "Documents/GitHub"
OUT = GH / "fish_par_combined_viewer"
WAVES = {
    "2017": GH / "fish_par_2017_viewer/survey_data_6_8_20.js",
    "2020": GH / "fish_par_2020_viewer/wcpData.js",
    "2023": GH / "fish_par_2023_viewer/wcpData.js",
    "2026": GH / "fish_par_2026_viewer/wcpData.js",
}

# ---- 1. wcpDataAll.js ----------------------------------------------------
parts = ["// Generated by build_combined.py - do not hand edit.",
         "// Source: fish_par_{2020,2023,2026}_viewer/wcpData.js",
         'var WCP = {"2017":{}, "2020":{}, "2023":{}, "2026":{}};']
decl = re.compile(r"^\s*let\s+(q[0-9_a-b]+)Data\s*=", re.M)
for year, path in WAVES.items():
    src = path.read_text()
    slots = decl.findall(src)
    rewritten = decl.sub(lambda m: 'WCP["%s"]["%s"] =' % (year, m.group(1)), src)
    parts.append(rewritten)
    print(year, "slots:", len(slots))
def headers(path):
    src = path.read_text()
    out = {}
    for m in re.finditer(r"let\s+(q[0-9_a-b]+)Data\s*=\s*\[\s*\n?\s*\[([^\]]*)\]", src):
        cols = [c.strip().strip("'\"") for c in m.group(2).split(",")]
        if cols and cols[-1] == "Cumulative":
            cols = cols[:-1]
        out[m.group(1)] = tuple(cols)
    return out

h17, h20 = headers(WAVES["2017"]), headers(WAVES["2020"])
# 2017 predates the fixed slot convention and its question numbering is shifted,
# so slots are matched to the 2020 convention by header content. A slot maps only
# when its header identifies exactly one slot on each side; anything ambiguous or
# unmatched is dropped rather than guessed.
from collections import Counter
c17, c20 = Counter(h17.values()), Counter(h20.values())
inv20 = {h: k for k, h in h20.items() if c20[h] == 1}
remap17 = {}
for k, h in sorted(h17.items()):
    if k in h20 and h17[k] == h20[k]:
        remap17[k] = k
    elif c17[h] == 1 and h in inv20:
        remap17[k] = inv20[h]
dropped17 = sorted(set(h17) - set(remap17))
renamed = {k: v for k, v in remap17.items() if k != v}
print("2017 slots mapped:", len(remap17), "| renamed:", renamed, "| dropped:", dropped17)
parts.append("// 2017 slot numbering is shifted relative to later waves; slots are")
parts.append("// remapped onto the 2020 convention by unique header match.")
parts.append("// Dropped as unmatched or ambiguous: " + ", ".join(dropped17))
parts.append("var REMAP_2017 = " + json.dumps(remap17) + ";")
parts.append('(function(){ var o = {}; Object.keys(REMAP_2017).forEach(function(k){ o[REMAP_2017[k]] = WCP["2017"][k]; }); WCP["2017"] = o; })();')
parts.append("""// Percent-bracket categories are exported in string order ("100%" sorts
// after "1-24%"); re-sort them numerically, keeping state groups intact.
(function(){
  var pct = /^(\d+)\s*(?:-\s*\d+)?\s*%$/;
  Object.keys(WCP).forEach(function(y){
    Object.keys(WCP[y]).forEach(function(slot){
      var d = WCP[y][slot];
      if (!d || d.length < 3) return;
      var rows = d.slice(1);
      if (!rows.every(function(r){ return pct.test(String(r[1])); })) return;
      var firstIdx = {};
      rows.forEach(function(r){ if (!(r[0] in firstIdx)) firstIdx[r[0]] = Object.keys(firstIdx).length; });
      rows.sort(function(a, b){
        if (firstIdx[a[0]] !== firstIdx[b[0]]) return firstIdx[a[0]] - firstIdx[b[0]];
        return parseInt(pct.exec(String(a[1]))[1], 10) - parseInt(pct.exec(String(b[1]))[1], 10);
      });
      WCP[y][slot] = [d[0]].concat(rows);
    });
  });
})();""")
# Per-slot y-axis maximum (percent) across every wave and state, so the axis
# does not rescale when the year toggle flips. Only single-select tables
# (State / category / Count / Percent) are pinned; matrix charts are left alone.
import csv as _csv, math
def slot_stats(path, remap=None):
    src = path.read_text()
    maxima, ordered = {}, {}
    VOCAB = ("Agree", "Dissatisf", "Satisf", "Important", "Always", "Mostly",
             "Sometimes", "Never", "Likely", "Helpful")
    for m in re.finditer(r"let\s+(q[0-9_a-b]+)Data\s*=\s*\[(.*?)^\s*\]", src, re.S | re.M):
        slot = remap.get(m.group(1)) if remap else m.group(1)
        if slot is None:
            continue
        rows = re.findall(r"\[([^\[\]]*)\]", m.group(2))
        if not rows:
            continue
        header = next(_csv.reader([rows[0]], quotechar="'", skipinitialspace=True))
        header = [h.strip().strip('"') for h in header]
        vals = header[2:]
        if len(vals) >= 3 and sum(any(v in h for v in VOCAB) for h in vals) >= 2:
            ordered[slot] = max(ordered.get(slot, 0), len(vals))
            continue
        if "Percent" not in header:
            continue
        pi = header.index("Percent")
        mx = 0.0
        for row in rows[1:]:
            try:
                cells = next(_csv.reader([row], quotechar="'", skipinitialspace=True))
                mx = max(mx, float(cells[pi]))
            except (ValueError, IndexError, StopIteration):
                pass
        if mx > 0:
            maxima[slot] = max(maxima.get(slot, 0), mx)
    return maxima, ordered

ymax, ordered_slots = {}, {}
for year, path in WAVES.items():
    mx, od = slot_stats(path, remap17 if year == "2017" else None)
    for k, v in mx.items():
        ymax[k] = max(ymax.get(k, 0), v)
    for k, v in od.items():
        ordered_slots[k] = max(ordered_slots.get(k, 0), v)
ymax = {k: min(100, int(math.ceil(v / 5.0)) * 5) for k, v in ymax.items()}
print("axis maxima computed for", len(ymax), "slots; ordered (Likert) slots:", sorted(ordered_slots))
parts.append("var YMAX = " + json.dumps(ymax) + ";")
parts.append("var ORDERED = " + json.dumps(sorted(ordered_slots)) + ";")
(OUT / "wcpDataAll.js").write_text("\n".join(parts))

# ---- 2. patch index.html -------------------------------------------------
html = (OUT / "index.html").read_text()

# data include
import time as _time
html = html.replace('<script src="wcpData.js"></script>',
                    '<script src="wcpDataAll.js?b=%d"></script>' % int(_time.time()))

# button id -> slot map, parsed from the existing click handlers
pairs = re.findall(r'\$\("#(question[0-9_a-b]+)"\)\.click\(function\(\)\{(.*?)\}\)', html, re.S)
qmap = {}
for bid, body in pairs:
    m = re.search(r"dash\.draw\((q[0-9_a-b]+)dt\)", body)
    if m:
        qmap[bid] = m.group(1)
print("button->slot pairs:", len(qmap))

# Responsive layout: flex columns instead of floated fixed widths.
old_show = '$("#dashboard").show();'
assert old_show in html
html = html.replace(old_show, '$("#dashboard").css("display", "flex");')


# Validated palette (dataviz reference instance): categorical fixed order.
m = re.search(r"var colorScheme = \[[^\]]*\];", html)
assert m, "colorScheme not found"
html = html.replace(m.group(0),
    "var colorScheme = ['#2a78d6','#eb6834','#1baf7a','#eda100','#e87ba4','#008300'];")

# Shrink the chart on narrow windows instead of a hard 850px.
assert "let defaultWidth = 850;" in html
html = html.replace("let defaultWidth = 850;",
    "let defaultWidth = document.documentElement.clientWidth < 980 ? Math.max(320, document.documentElement.clientWidth - 60) : Math.max(480, Math.min(850, document.documentElement.clientWidth - 380));")

# The dashboard ready listener is the terminal redraw point: append the
# respondent-count note and compare-mode redraw there so they follow every
# question, state, or year change (dash.draw is asynchronous).
old_ready = "\t\t\tvar dt = dashTable.getDataTable();\n\t\t\tdrawTable(dt);\n\t\t\tdrawChart(dt);\n\t\t})"
assert old_ready in html, "ready listener anchor"
html = html.replace(old_ready,
    "\t\t\tvar dt = dashTable.getDataTable();\n\t\t\tdrawTable(dt);\n\t\t\tdrawChart(dt);\n\t\t\tupdateN(dt);\n\t\t\tdrawCompareIfOn();\n\t\t})")


# replace the qNdt declaration block with a rebuildable table store
dt_line = re.compile(r"^\s*let\s+q[0-9_a-b]+dt\s*=\s*google\.visualization\.arrayToDataTable\(q[0-9_a-b]+Data,false\);\s*$\n?", re.M)
n_decl = len(dt_line.findall(html))
store = """\t\tvar WCP_DT = {};
\t\tfunction rebuildDataTables(y){
\t\t\tObject.keys(WCP[y]).forEach(function(slot){
\t\t\t\tWCP_DT[slot] = google.visualization.arrayToDataTable(WCP[y][slot], false);
\t\t\t});
\t\t}
\t\trebuildDataTables(String(surveyYear));
"""
html, count = dt_line.subn("", html)
assert count == n_decl and count > 40, count
# insert the store right after the surveyYear declaration
html = html.replace("let surveyYear = 2026;", "var surveyYear = 2026;\n" + store, 1)

# route every dash.draw through the store
html = re.sub(r"dash\.draw\((q[0-9_a-b]+)dt\)", lambda m: 'dash.draw(WCP_DT["%s"])' % m.group(1), html)

# ---- 3. year control + caveats ------------------------------------------
year_js = """
\t\t// ---- combined-viewer year control (prototype) ----
\t\tvar QMAP = %(qmap)s;
\t\tvar REF_YEARS = {"2017":"2016","2020":"2019","2023":"2022","2026":"2025"};
\t\tvar BASE_NOTE = "Question wording shown is from the 2026 survey; wording and response options vary slightly between years. Questions asked only in 2017 or 2020 are not yet included, and 2017 charts cover only the questions verified to match later waves.";
\t\tvar CAVEATS = {
\t\t\t"2017": {"q8": "Caution: the direction of this scale in the 2017 data has not been verified against later years. Compare across years with care."},
\t\t\t"2023": {"q8": "Caution: in the 2023 data shown here the proportion-of-contacts scale runs in the reverse direction from 2020 and 2026. Do not compare this chart across years until the 2023 data are rebuilt."},
\t\t\t"2026": {"q3": "The 2026 survey dropped the \\"As long as I can\\" option, so this chart has one fewer category than earlier years."}
\t\t};

\t\t$("#stateFilter").after('<div id="yearFilter" style="margin:10px 0 4px 0;"><div style="font-weight:bold;">Survey Year</div>' +
\t\t\t["2017","2020","2023","2026"].map(function(y){
\t\t\t\treturn '<label style="margin-right:10px;"><input type="radio" name="wcpYear" value="' + y + '"' + (y === String(surveyYear) ? " checked" : "") + '> ' + y + '</label>';
\t\t\t}).join("") + '</div>');
\t\t$("#qStateHeader").after('<div id="yearCaveat" style="max-width:850px; margin-top:6px; font-size:85%%; color:#8a6d3b; background:#fcf8e3; border:1px solid #faebcc; border-radius:3px; padding:4px 8px; display:none;"></div>');

\t\tfunction updateCaveat(qid){
\t\t\tvar slot = QMAP[qid || $(".selectedQuestion").attr("id")];
\t\t\tvar msg = (CAVEATS[String(surveyYear)] || {})[slot];
\t\t\tif (msg) { $("#yearCaveat").text(msg).show(); } else { $("#yearCaveat").hide(); }
\t\t}

\t\tfunction setSurveyYear(y){
\t\t\ty = String(y);
\t\t\tvar oldY = String(surveyYear), oldRef = REF_YEARS[oldY];
\t\t\t$(".question").each(function(){
\t\t\t\t$(this).text($(this).text().split(oldY).join(y).split(oldRef).join(REF_YEARS[y]));
\t\t\t});
\t\t\tsurveyYear = Number(y);
\t\t\trebuildDataTables(y);
\t\t\t$(".question").each(function(){
\t\t\t\tvar slot = QMAP[this.id];
\t\t\t\tvar ok = !!(slot && WCP[y][slot]);
\t\t\t\t$(this).prop("disabled", !ok).css("opacity", ok ? 1 : 0.4)
\t\t\t\t\t.attr("title", ok ? "" : "Not asked in the " + y + " survey");
\t\t\t});
\t\t\tvar cur = $(".selectedQuestion");
\t\t\tif (cur.length && !cur.prop("disabled")) { cur.click(); } else { $("#question1").click(); }
\t\t\tupdateCaveat();
\t\t}

\t\t$(document).on("change", "input[name=wcpYear]", function(){ setSurveyYear(this.value); });
\t\t$(".question").click(function(){ CURRENT_SLOT = QMAP[this.id] || CURRENT_SLOT; updateCaveat(this.id); });
\t\tfunction chartWidth(){
\t\t\tvar cw = document.documentElement.clientWidth;
\t\t\treturn cw < 980 ? Math.max(320, cw - 60) : Math.max(480, Math.min(850, cw - 380));
\t\t}
\t\tvar _rsz;
\t\t$(window).on("resize", function(){
\t\t\tclearTimeout(_rsz);
\t\t\t_rsz = setTimeout(function(){
\t\t\t\tvar w = chartWidth();
\t\t\t\tif (Math.abs(w - defaultWidth) < 8) return;
\t\t\t\tdefaultWidth = w;
\t\t\t\tqChart.setOption("width", defaultWidth);
\t\t\t\tvar cur = $(".selectedQuestion");
\t\t\t\tif (cur.length && !cur.prop("disabled")) { cur.click(); } else { $("#question1").click(); }
\t\t\t}, 250);
\t\t});

\t\t// ---- quality pass: pinned axes, ordinal ramps, n note, compare mode ----
\t\tvar CURRENT_SLOT = "q1";
\t\tvar BLUE_RAMP = ["#86b6ef","#6da7ec","#5598e7","#3987e5","#2a78d6","#256abf","#1c5cab","#184f95","#104281","#0d366b"];
\t\tfunction ordinalRamp(n){
\t\t\tvar out = [];
\t\t\tfor (var i = 0; i < n; i++) out.push(BLUE_RAMP[Math.round(i * (BLUE_RAMP.length - 1) / Math.max(1, n - 1))]);
\t\t\treturn out;
\t\t}
\t\tvar WAVE_COLORS = {"2017":"#2a78d6","2020":"#eb6834","2023":"#1baf7a","2026":"#eda100"};
\t\tvar COMPARE_ACTIVE = false;

\t\tvar _qChartDraw = qChart.draw.bind(qChart);
\t\tqChart.draw = function(){
\t\t\tif (!COMPARE_ACTIVE) {
\t\t\t\tvar dtv = qChart.getDataTable();
\t\t\t\tvar ncols = dtv ? dtv.getNumberOfColumns() : 0;
\t\t\t\tif (ncols === 2 && YMAX[CURRENT_SLOT]) {
\t\t\t\t\tqChart.setOption("vAxis.maxValue", YMAX[CURRENT_SLOT]);
\t\t\t\t\tqChart.setOption("vAxis.minValue", 0);
\t\t\t\t} else {
\t\t\t\t\tqChart.setOption("vAxis.maxValue", null);
\t\t\t\t}
\t\t\t\tif (ncols > 2 && ORDERED.indexOf(CURRENT_SLOT) > -1) {
\t\t\t\t\tqChart.setOption("colors", ordinalRamp(ncols - 1));
\t\t\t\t} else {
\t\t\t\t\tqChart.setOption("colors", colorScheme);
\t\t\t\t}
\t\t\t}
\t\t\tfixLabels();
\t\t\t_qChartDraw();
\t\t};

\t\tfunction wrapLabel(str, width){
\t\t\tif (typeof str !== "string" || str.length <= width) return str;
\t\t\tvar words = str.split(" "), lines = [], cur = "";
\t\t\twords.forEach(function(w){
\t\t\t\tif (cur && (cur + " " + w).length > width) { lines.push(cur); cur = w; }
\t\t\t\telse cur = cur ? cur + " " + w : w;
\t\t\t});
\t\t\tif (cur) lines.push(cur);
\t\t\treturn lines.join("\\n");
\t\t}
\t\tfunction fixLabels(){
\t\t\tvar dtv = qChart.getDataTable();
\t\t\tif (!dtv || !dtv.getNumberOfRows()) return;
\t\t\tvar maxLen = 0, r;
\t\t\tfor (r = 0; r < dtv.getNumberOfRows(); r++)
\t\t\t\tmaxLen = Math.max(maxLen, String(dtv.getValue(r, 0) || "").length);
\t\t\tif (maxLen <= 16) return;
\t\t\tvar flat = dtv.toDataTable ? dtv.toDataTable() : dtv.clone();
\t\t\tvar width = maxLen > 60 ? 28 : maxLen > 34 ? 22 : 16;
\t\t\tvar maxLines = 1;
\t\t\tfor (r = 0; r < flat.getNumberOfRows(); r++) {
\t\t\t\tvar w = wrapLabel(String(flat.getValue(r, 0) || ""), width);
\t\t\t\tmaxLines = Math.max(maxLines, w.split("\\n").length);
\t\t\t\tflat.setValue(r, 0, w);
\t\t\t}
\t\t\tqChart.setDataTable(flat);
\t\t\tvar ct = qChart.getChartType();
\t\t\tif (ct === "ColumnChart") {
\t\t\t\tqChart.setOption("chartArea.bottom", Math.min(200, 44 + 15 * maxLines));
\t\t\t\tqChart.setOption("hAxis.slantedText", false);
\t\t\t} else if (ct === "BarChart") {
\t\t\t\tqChart.setOption("chartArea.left", Math.min(300, 70 + 7.2 * Math.min(maxLen, width)));
\t\t\t\tqChart.setOption("chartArea.bottom", 64);
\t\t\t}
\t\t}

\t\t// Narrow tables stay narrow; matrix tables get room.
\t\tvar _qTableDraw = qTable.draw.bind(qTable);
\t\tqTable.draw = function(){
\t\t\tvar dtv = qTable.getDataTable();
\t\t\tvar ncols = dtv ? dtv.getNumberOfColumns() : 0;
\t\t\tvar tMax = 0;
\t\t\tif (dtv) for (var tr = 0; tr < dtv.getNumberOfRows(); tr++)
\t\t\t\ttMax = Math.max(tMax, String(dtv.getValue(tr, 0) || "").length);
\t\t\tqTable.setOption("width", ncols > 3 ? Math.min(940, defaultWidth + 90) : tMax > 45 ? 800 : tMax > 22 ? 640 : 480);
\t\t\t_qTableDraw();
\t\t};

\t\tfunction updateN(dt){
\t\t\tif (!$("#nNote").length) $("#qStateHeader").after('<div id="nNote" style="color:#666;font-size:90%%;margin:2px 0 8px;"></div>');
\t\t\tvar ci = -1;
\t\t\tfor (var i = 0; i < dt.getNumberOfColumns(); i++) if (dt.getColumnLabel(i) === "Count") ci = i;
\t\t\tif (ci < 0) { $("#nNote").hide(); return; }
\t\t\tvar n = 0;
\t\t\tfor (var r = 0; r < dt.getNumberOfRows(); r++) n += dt.getValue(r, ci) || 0;
\t\t\t$("#nNote").text("n = " + n.toLocaleString() + " answered this question in the " + surveyYear + " survey").show();
\t\t}

\t\t// State radios drive the hidden CategoryFilter so the dashboard machinery
\t\t// stays untouched.
\t\t$("#stateFilter").css({position: "absolute", left: "-9999px"});
\t\t$("#stateFilter").after('<div id="stateRadios"><div style="font-weight:bold;">State</div>' +
\t\t\t[["All","All"],["CA","California"],["OR","Oregon"],["WA","Washington"]].map(function(sv){
\t\t\t\treturn '<label style="margin-right:8px; white-space:nowrap;"><input type="radio" name="wcpState" value="' + sv[0] + '"' + (sv[0] === "All" ? " checked" : "") + '> ' + sv[1] + '</label>';
\t\t\t}).join("") + '</div>');
\t\t$(document).on("change", "input[name=wcpState]", function(){
\t\t\tstateFilter.setState({selectedValues: [this.value]});
\t\t\tstateFilter.draw();
\t\t});

\t\t// Compare-years mode: grouped bars, one series per wave, joined on the
\t\t// response category. Single-select questions only.
\t\t$("#yearFilter").append('<label style="display:block; margin-top:4px;"><input type="checkbox" id="compareYears"> Compare years side by side</label>');
\t\tfunction compareYearsFor(slot){
\t\t\treturn ["2017","2020","2023","2026"].filter(function(y){
\t\t\t\tvar d = WCP[y][slot];
\t\t\t\treturn d && d[0].indexOf("Percent") > -1 && ORDERED.indexOf(slot) < 0;
\t\t\t});
\t\t}
\t\tfunction drawCompareIfOn(){
\t\t\tCOMPARE_ACTIVE = $("#compareYears").prop("checked");
\t\t\tif (!COMPARE_ACTIVE) { $("#compareNote").hide(); return; }
\t\t\tvar slot = CURRENT_SLOT;
\t\t\tvar yrs = compareYearsFor(slot);
\t\t\tif (!$("#compareNote").length) $("#nNote").after('<div id="compareNote" style="color:#666;font-size:90%%;margin:2px 0 8px;"></div>');
\t\t\tif (yrs.length < 2) {
\t\t\t\t$("#compareNote").text("Year comparison is not available for this question.").show();
\t\t\t\tCOMPARE_ACTIVE = false;
\t\t\t\treturn;
\t\t\t}
\t\t\tvar st = $("input[name=wcpState]:checked").val() || "All";
\t\t\tvar cats = [], vals = {};
\t\t\tyrs.forEach(function(y){
\t\t\t\tvar d = WCP[y][slot], pi = d[0].indexOf("Percent");
\t\t\t\tfor (var r = 1; r < d.length; r++) {
\t\t\t\t\tif (String(d[r][0]) !== st) continue;
\t\t\t\t\tvar c = String(d[r][1]);
\t\t\t\t\tif (!(c in vals)) { vals[c] = {}; cats.push(c); }
\t\t\t\t\tvals[c][y] = d[r][pi];
\t\t\t\t}
\t\t\t});
\t\t\tvar arr = [["Category"].concat(yrs)];
\t\t\tcats.forEach(function(c){
\t\t\t\tarr.push([c].concat(yrs.map(function(y){ return (vals[c][y] == null ? null : vals[c][y]); })));
\t\t\t});
\t\t\tqChart.setChartType("ColumnChart");
\t\t\tqChart.setOption("chartArea", {left: 70, right: 170, top: 40, bottom: 60});
\t\t\tqChart.setOption("height", defaultHeight);
\t\t\tqChart.setOption("width", defaultWidth);
\t\t\tqChart.setOption("colors", yrs.map(function(y){ return WAVE_COLORS[y]; }));
\t\t\tqChart.setOption("legend.position", "right");
\t\t\tqChart.setOption("vAxis.maxValue", YMAX[slot] || null);
\t\t\tqChart.setOption("vAxis.minValue", 0);
\t\t\tqChart.setOption("title", "Percent of responses by survey year");
\t\t\tqChart.setDataTable(google.visualization.arrayToDataTable(arr));
\t\t\tqChart.draw();
\t\t\t$("#compareNote").text("Comparing " + yrs.join(", ") + ". Question wording and response options can differ between years - see the note above the chart.").show();
\t\t}
\t\t$(document).on("change", "#compareYears", function(){ drawCompareIfOn(); if (!this.checked) $(".selectedQuestion").length ? $(".selectedQuestion").click() : $("#question1").click(); });
""" % {"qmap": json.dumps(qmap)}

anchor = 'dash.draw(WCP_DT["q1"])'
idx = html.rindex(anchor)          # the init draw near the end
end = idx + len(anchor)
html = html[:end] + "\n" + year_js + html[end:]

html = ('<meta charset="utf-8">\n<style>'
    'button.question:focus-visible, input:focus-visible{outline:3px solid #2a78d6; outline-offset:2px;} '
    '#yearFilter label, #stateRadios label{cursor:pointer;} '
    '#dashboard{align-items:flex-start; gap:14px; flex-wrap:wrap;} '
    '.filterBox{float:none; flex:0 0 300px;} '
    '.surveyVisual{float:none; width:auto; flex:1 1 480px; min-width:0;} '
    '.surveyChartBox{float:none; max-width:100%;} '
    '#qChart, #qTable{overflow-x:auto; max-width:100%;} '
    '@media (max-width: 979px){ #q1Filters{flex-basis:100%; max-width:none;} }'
    '</style>\n') + html
(OUT / "index.html").write_text(html)
print("index.html patched")
